apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: nimishgsk/backend:latest
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "fullstack"
        - name: DB_USER
          value: "CEO"
        - name: DB_PASSWORD
          value: "CEO_Str0ng@2024!"
